<?php

return [
    'countries' => array(
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "BQ" => "British Antarctic Territory",
        "IO" => "British Indian Ocean Territory",
        "VG" => "British Virgin Islands",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CT" => "Canton and Enderbury Islands",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos [Keeling] Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo - Brazzaville",
        "CD" => "Congo - Kinshasa",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "CI" => "Côte d’Ivoire",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "NQ" => "Dronning Maud Land",
        "DD" => "East Germany",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "FQ" => "French Southern and Antarctic Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong SAR China",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JT" => "Johnston Island",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macau SAR China",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "FX" => "Metropolitan France",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MI" => "Midway Islands",
        "MD" => "Moldova",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar [Burma]",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NT" => "Neutral Zone",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "KP" => "North Korea",
        "VD" => "North Vietnam",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PC" => "Pacific Islands Trust Territory",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territories",
        "PA" => "Panama",
        "PZ" => "Panama Canal Zone",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "YD" => "People's Democratic Republic of Yemen",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn Islands",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RO" => "Romania",
        "RU" => "Russia",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "CS" => "Serbia and Montenegro",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "KR" => "South Korea",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "ST" => "São Tomé and Príncipe",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UM" => "U.S. Minor Outlying Islands",
        "PU" => "U.S. Miscellaneous Pacific Islands",
        "VI" => "U.S. Virgin Islands",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "SU" => "Union of Soviet Socialist Republics",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" => "United States",
        "ZZ" => "Unknown or Invalid Region",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WK" => "Wake Island",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "AX" => "Åland Islands",
    ),

    'states' => [
        'AU' => ['Australian Capital Territory', 'New South Wales', 'Northern Territory', 'Queensland',  'South Australia', 'Tasmania', 'Victoria', 'Western Australia'],
        'CA' => ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon'],
        'IN' => ['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Ladakh', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
        'NZ' => ['Auckland', 'Bay of Plenty', 'Canterbury', 'Gisborne', 'Hawke`s Bay', 'Manawatu-Whanganui', 'Marlborough', 'Nelson', 'Northland', 'Otago', 'Southland', 'Taranaki', 'Tasman', 'Waikato', 'Wellington†', 'West Coast'],
        'US' => ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']
    ],

    'place_of_supply_codes' => [
        'IN' => [
            'Andaman and Nicobar Islands' => "35",
            'Andhra Pradesh' => "37",
            'Arunachal Pradesh' => "12",
            'Assam' => "18",
            'Bihar' => "10",
            'Chandigarh' => "04",
            'Chhattisgarh' => "22",
            'Dadra and Nagar Haveli' => "26",
            'Daman and Diu' => "25",
            'Goa' => "30",
            'Gujarat' => "24",
            'Haryana' => "06",
            'Himachal Pradesh' => "02",
            'Jammu and Kashmir' => "01",
            'Jharkhand' => "20",
            'Karnataka' => "29",
            'Kerala' => "32",
            'Lakshadweep' => "31",
            'Ladakh' => "38",
            'Madhya Pradesh' => "23",
            'Maharashtra' => "27",
            'Manipur' => "14",
            'Meghalaya' => "17",
            'Mizoram' => "15",
            'Nagaland' => "13",
            'Delhi' => "07",
            'Odisha' => "21",
            'Puducherry' => "34",
            'Punjab' => "03",
            'Rajasthan' => "08",
            'Sikkim' => "11",
            'Tamil Nadu' => "33",
            'Telangana' => "36",
            'Tripura' => "16",
            'Uttar Pradesh' => "09",
            'Uttarakhand' => "05",
            'West Bengal' => "19",
        ],
        'US' => [
            'Taxes' => '895',
            'Florida' => '4469',
        ]
    ],

    'categories' => [
        "it" => "IT",
        "pharma" => "Pharma",
        "fmcg" => "FMCG",
        "chemical" => "Chemical Industry",
        "mechanical" => "Mechanical Industry",
        "electrical" => "Electrical Industry",
        "other" => "Others"
    ],

    'payment_mode' => [
        "net-banking" => "NetBanking",
        "upi" => "UPI",
        "cheque" => "Cheque",
    ],

    'payment_history' => [
        "payment_created" => "created",
        "payment_added" => "added",
        "payment_refund" => "refunded",
    ],

    'roles' => [
        // "manager" => "Manager",
        "employee" => "Employee",
        "staff" => "Staff",
        'account_manager' => 'Account Manager',
        'broker' => 'Broker',
        'NSE User' => 'NSE User',
    ],

    'business_of_broker' => [
        "Individual" => "Individual",
        "Partnership Firm" => "Partnership Firm",
        "Proprietorship Firm" => "Proprietorship Firm",
        'Company' => 'Company',
        'HUF' => 'HUF',
        'LLP' => 'LLP',
        "Firm" => "Firm",
    ],
    'gst_compliant' => [
        "yes" => "Yes",
        "no" => "No",
    ],

    'reports' => [
        "employee_report" => "Employee Report",
        "broker_report" => "Broker Report",
        "share_report" => "Share Report",
        "inventory_report" => "Profit Report",
    ],

    'reference' => [
        "hottel.in" => "hottel.in",
        "InvestorZone.in" => "InvestorZone.in",
        "google_search" => "Google Search",
        "youtube" => "YouTube",
        "newspaper" => "Newspaper",
        "existing_user" => "Existing UZLive User",
        "other" => "Others",
    ],

   

    'userfilter' => [
        "verified" => "Verified",
        "unverified" => "Unverified",
        "admin" => "Admin",
        "enable" => "Enabled",
        "disable" => "Disabled",
        "document_upload" => "Documents Uploaded",
        "wrong_document" => "Wrong Document",

    ],

    'userfilterlastlogin' => [
        "in_last_24_hour" => "In last 24 Hrs",
        "in_last_48_hour" => "In last 48 Hrs",
        "in_last_1_week" => "In last 1 week",
        "in_last_1_months" => "In last 1 month",
        "not_in_last_1_months" => "Not In last 1 month",
        "not_in_last_3_months" => "Not In last 3 months",

    ],

    'order_status' => [
        "live" => ["name" => "Live", "class" => "label label-lg label-light-primary label-inline"],
        "moderation" => ["name" => "Moderation", "class" => "label label-lg label-light-warning label-inline"],
        "expired" => ["name" => "Expired", "class" => "label label-lg label-light-danger label-inline"],
        "executed" => ["name" => "Executed", "class" => "label label-lg label-light-success label-inline"],
    ],

    'order_type' => [
        "buy" => ["name" => "Buy"],
        "sell" => ["name" => "Sell"],
    ],


    'currencies' => [
        'INR' => ['code' => '&#8377;', 'name' => 'Indian Rupee'],
        'USD' => ['code' => '$', 'name' => 'US Dollar'],
        'EUR' => ['code' => '&#x20AC;', 'name' => 'EURO'],
        'GBP' => ['code' => '&#xa3;', 'name' => 'Pound Sterling'],
        'YEN' => ['code' => '&#165;', 'name' => 'Japanese Yen'], // not supported by razorpay
        'AUD' => ['code' => '$', 'name' => 'Australian Dollar'],
        'CAD' => ['code' => '$', 'name' => 'Canadian Dollar'],
        'NZD' => ['code' => '$', 'name' => 'New Zealand Dollar'],
        'SGD' => ['code' => '$', 'name' => 'Singapore Dollar'],
        'HKD' => ['code' => '$', 'name' => 'Hongkong Dollar'],
        'THB' => ['code' => '฿', 'name' => 'Thai Baht'],
        'MYR' => ['code' => 'RM', 'name' => 'Malaysian Ringgit'],
        'CNY' => ['code' => '¥', 'name' => 'Chinese Yuan'], //Popular currencies end here...
        'AED' => ['code' => '&#x62f;&#x2e;&#x625;', 'name' => 'UAE Dirham'],
        'AFN' => ['code' => 'Af', 'name' => 'Afghani'],
        'ALL' => ['code' => 'L', 'name' => 'Albanian Lek'],
        'AMD' => ['code' => '&#1423;', 'name' => 'Armenian Dram'],
        'AOA' => ['code' => 'Kz', 'name' => 'Angolian Kwanza'],
        'ARS' => ['code' => '$', 'name' => 'Argentine Peso'],
        'AWG' => ['code' => 'ƒ', 'name' => 'Aruban Guilder/Florin'],
        'AZN' => ['code' => '&#8380;', 'name' => 'Azerbaijanian Manat'],
        'BAM' => ['code' => 'КМ', 'name' => 'Konvertibilna Marka'],
        'BBD' => ['code' => '$', 'name' => 'Barbados Dollar'],
        'BDT' => ['code' => '&#2547;', 'name' => 'Bangladeshi Taka'],
        'BGN' => ['code' => 'лв', 'name' => 'Bulgarian Lev'],
        'BHD' => ['code' => 'Dinar', 'name' => 'Bahraini Dinar'],
        'BMD' => ['code' => '$', 'name' => 'Bermudian Dollar'],
        'BND' => ['code' => '$', 'name' => 'Brunei Dollar'],
        'BRL' => ['code' => 'R$', 'name' => 'Brazilian Real'],
        'CHF' => ['code' => 'CHF', 'name' => 'Swiss Franc'],
        'FJD' => ['code' => '$', 'name' => 'Fiji Dollar'],
        'HRK' => ['code' => 'Kn', 'name' => 'Croatian Kuna'],
        'IDR' => ['code' => 'Rp', 'name' => 'Indonesian Rupiah'],
        'IQD' => ['code' => 'IQD', 'name' => 'Iraqi Dinar'],
        'IRR' => ['code' => 'IRR', 'name' => 'Iranian Rial'],
        'ISK' => ['code' => 'Kr', 'name' => 'Iceland Krona'],
        'JMD' => ['code' => '$', 'name' => 'Jamaican Dollar'],
        'JOD' => ['code' => 'JOD', 'name' => 'Jordanian Dinar'],
        'NGN' => ['code' => '&#8358;', 'name' => 'Nigeria Naira'],
        'KRW' => ['code' => '&#8361;', 'name' => 'South Korean Won'],
        'KWD' => ['code' => 'د.ك', 'name' => 'Kuwaiti Dinar'],
        'LKR' => ['code' => 'Rs', 'name' => 'Sri Lanka Rupee'],
        'MUR' => ['code' => 'Rs', 'name' => 'Mauritius Rupee'],
        'MXN' => ['code' => '$', 'name' => 'Mexican Peso'],
        'PHP' => ['code' => '&#8369;', 'name' => 'Philippine Peso'],
        'QAR' => ['code' => '&#65020;', 'name' => 'Qatari Rial'],
        'RUB' => ['code' => '&#8381;', 'name' => 'Russian Ruble'],
        'SAR' => ['code' => '&#65020;', 'name' => 'Saudi Riyal'],
        'SEK' => ['code' => 'kr', 'name' => 'Swedish Krona'],
        'UAH' => ['code' => '&#8372;', 'name' => 'Ukraine Hryvnia'],
        'ZAR' => ['code' => 'R', 'name' => 'South African Rand'],
    ],

    'payment_gateways' => ['paypal', 'stripe', 'razorpay'],
    'timezones' => [
        "Etc/GMT+12" => "(GMT-12:00) International Date Line West",
        "Pacific/Midway" => "(GMT-11:00) Midway Island, Samoa",
        "Pacific/Honolulu" => "(GMT-10:00) Hawaii",
        "US/Alaska" => "(GMT-09:00) Alaska",
        "America/Los_Angeles" => "(GMT-08:00) Pacific Time (US & Canada)",
        "America/Tijuana" => "(GMT-08:00) Tijuana, Baja California",
        "US/Arizona" => "(GMT-07:00) Arizona",
        "America/Chihuahua" => "(GMT-07:00) Chihuahua, La Paz, Mazatlan",
        "US/Mountain" => "(GMT-07:00) Mountain Time (US & Canada)",
        "America/Managua" => "(GMT-06:00) Central America",
        "US/Central" => "(GMT-06:00) Central Time (US & Canada)",
        "America/Mexico_City" => "(GMT-06:00) Guadalajara, Mexico City, Monterrey",
        "Canada/Saskatchewan" => "(GMT-06:00) Saskatchewan",
        "America/Bogota" => "(GMT-05:00) Bogota, Lima, Quito, Rio Branco",
        "US/Eastern" => "(GMT-05:00) Eastern Time (US & Canada)",
        "US/East-Indiana" => "(GMT-05:00) Indiana (East)",
        "Canada/Atlantic" => "(GMT-04:00) Atlantic Time (Canada)",
        "America/Caracas" => "(GMT-04:00) Caracas, La Paz",
        "America/Manaus" => "(GMT-04:00) Manaus",
        "America/Santiago" => "(GMT-04:00) Santiago",
        "Canada/Newfoundland" => "(GMT-03:30) Newfoundland",
        "America/Sao_Paulo" => "(GMT-03:00) Brasilia",
        "America/Argentina/Buenos_Aires" => "(GMT-03:00) Buenos Aires, Georgetown",
        "America/Godthab" => "(GMT-03:00) Greenland",
        "America/Montevideo" => "(GMT-03:00) Montevideo",
        "America/Noronha" => "(GMT-02:00) Mid-Atlantic",
        "Atlantic/Cape_Verde" => "(GMT-01:00) Cape Verde Is.",
        "Atlantic/Azores" => "(GMT-01:00) Azores",
        "Africa/Casablanca" => "(GMT+00:00) Casablanca, Monrovia, Reykjavik",
        "Etc/Greenwich" => "(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London",
        "Europe/Amsterdam" => "(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
        "Europe/Belgrade" => "(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
        "Europe/Brussels" => "(GMT+01:00) Brussels, Copenhagen, Madrid, Paris",
        "Europe/Sarajevo" => "(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb",
        "Africa/Lagos" => "(GMT+01:00) West Central Africa",
        "Asia/Amman" => "(GMT+02:00) Amman",
        "Europe/Athens" => "(GMT+02:00) Athens, Bucharest, Istanbul",
        "Asia/Beirut" => "(GMT+02:00) Beirut",
        "Africa/Cairo" => "(GMT+02:00) Cairo",
        "Africa/Harare" => "(GMT+02:00) Harare, Pretoria",
        "Europe/Helsinki" => "(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
        "Asia/Jerusalem" => "(GMT+02:00) Jerusalem",
        "Europe/Minsk" => "(GMT+02:00) Minsk",
        "Africa/Windhoek" => "(GMT+02:00) Windhoek",
        "Asia/Kuwait" => "(GMT+03:00) Kuwait, Riyadh, Baghdad",
        "Europe/Moscow" => "(GMT+03:00) Moscow, St. Petersburg, Volgograd",
        "Africa/Nairobi" => "(GMT+03:00) Nairobi",
        "Asia/Tbilisi" => "(GMT+03:00) Tbilisi",
        "Asia/Tehran" => "(GMT+03:30) Tehran",
        "Asia/Muscat" => "(GMT+04:00) Abu Dhabi, Muscat",
        "Asia/Baku" => "(GMT+04:00) Baku",
        "Asia/Yerevan" => "(GMT+04:00) Yerevan",
        "Asia/Kabul" => "(GMT+04:30) Kabul",
        "Asia/Yekaterinburg" => "(GMT+05:00) Yekaterinburg",
        "Asia/Karachi" => "(GMT+05:00) Islamabad, Karachi, Tashkent",
        "Asia/Calcutta" => "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi",
        "Asia/Colombo" => "(GMT+05:30) Sri Jayawardenapura",
        "Asia/Katmandu" => "(GMT+05:45) Kathmandu",
        "Asia/Almaty" => "(GMT+06:00) Almaty, Novosibirsk",
        "Asia/Dhaka" => "(GMT+06:00) Astana, Dhaka",
        "Asia/Rangoon" => "(GMT+06:30) Yangon (Rangoon)",
        "Asia/Bangkok" => "(GMT+07:00) Bangkok, Hanoi, Jakarta",
        "Asia/Krasnoyarsk" => "(GMT+07:00) Krasnoyarsk",
        "Asia/Hong_Kong" => "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi",
        "Asia/Kuala_Lumpur" => "(GMT+08:00) Kuala Lumpur, Singapore",
        "Asia/Irkutsk" => "(GMT+08:00) Irkutsk, Ulaan Bataar",
        "Australia/Perth" => "(GMT+08:00) Perth",
        "Asia/Taipei" => "(GMT+08:00) Taipei",
        "Asia/Tokyo" => "(GMT+09:00) Osaka, Sapporo, Tokyo",
        "Asia/Seoul" => "(GMT+09:00) Seoul",
        "Asia/Yakutsk" => "(GMT+09:00) Yakutsk",
        "Australia/Adelaide" => "(GMT+09:30) Adelaide",
        "Australia/Darwin" => "(GMT+09:30) Darwin",
        "Australia/Brisbane" => "(GMT+10:00) Brisbane",
        "Australia/Canberra" => "(GMT+10:00) Canberra, Melbourne, Sydney",
        "Australia/Hobart" => "(GMT+10:00) Hobart",
        "Pacific/Guam" => "(GMT+10:00) Guam, Port Moresby",
        "Asia/Vladivostok" => "(GMT+10:00) Vladivostok",
        "Asia/Magadan" => "(GMT+11:00) Magadan, Solomon Is., New Caledonia",
        "Pacific/Auckland" => "(GMT+12:00) Auckland, Wellington",
        "Pacific/Fiji" => "(GMT+12:00) Fiji, Kamchatka, Marshall Is.",
        "Pacific/Tongatapu" => "(GMT+13:00) Nuku'alofa",
    ],
    'knowledge_center_categories' => [
        'Videos' => 'Videos',
        'Blogs' => 'Blogs',
        'News' => 'News',
        'Documents' => 'Documents',
        'Learn More' => 'Learn More',
    ],
    'blog_categories' => [
        'financial_analysis'    => 'Financial Analysis',
        'information'           => 'Information',
        'lava'                  => 'Lava',
        'news'                  => 'News',
        'pharmeasy'             => 'Pharmeasy',
        'startup_stories'       => 'Startup Stories'
    ],
    'business_type' => [
        "Partnership Firm" => "Partnership Firm",
        "Proprietorship Firm" => "Proprietorship Firm",
        'Company' => 'Company',
        'HUF' => 'HUF',
        'LLP' => 'LLP',

    ],
    'corporate_action' => [
        "bonus" => "bonus",
        "split" => "split",
        'dividend' => 'dividend',
        'corporate_action' => 'Corporate Action'
    ],

    'company_category' => [
        "banking" => "Banking",
        "non_banking" => "non Banking",
        "insurance" => 'Insurance',
    ],
    'company_sectors' => [
        'banking' => [
            'banking' => 'Banking'
        ],
        'non_banking' => [
            'energy'        => 'Energy',
            'communication' => 'Communication',
            'automobile'    => 'Automobile',
            'entertainment' => 'Entertainment',
            'education'     => 'Education'
        ],
        'insurance' => [
            'insurance'     => 'Insurance'
        ]
    ],
    'sector_icon' => [
        'banking'       => 'bank.png',
        'communication' => 'discussion.png',
        'energy'        => 'solar-energy.png',
        'automobile'    => 'Group.png',
        'entertainment' => 'theatre-mask.png',
        'education'     => 'education.png',
        'insurance'     => 'solar-energy.png',
        'uncategorise'  => 'Group.png'
    ],
    'quarter_financial_year' => [
        "Quarter-1" => "Quarter-1",
        "Quarter-2" => "Quarter-2",
        "Quarter-3" => "Quarter-3",
        "Quarter-4" => "Quarter-4",
    ],
    'screener_value_in_rupees' => [
        "lk" => "lk",
        "cr" => "cr",
    ],

    'screener_ratios' => [
        "market_cap_cr" => "Market Cap (Cr)",
        "p_e" => "P / E",
        "book_value" => "book_value",
        "roce" => "ROCE",
        "roe" => "ROE",
        "3_year_revenue_cagr" => "3 Years Revenue CAGR",
        "3_year_pat_cagr" => "3 Years PAT CAGR",
        "cfo_ebitda" => "CFO/EBITDA",
        "d_e" => "D / E",
    ],
    'shareholding-pattern' => [
        'domestic'          => 'Domestic',
        'foreign'           => 'Foreign',
        'institutional'     => 'Institutional',
        'non-institutional' => 'Non-institutional'
    ],
    'promoters_designation' => [
        'ceo'   => 'Chief Executive Officer (CEO)',
        'coo'   => 'Chief Operating Officer (COO)',
        'cfo'   => 'Chief Financial Officer (CFO)',
        'cio'   => 'Chief Information Officer (CIO)',
        'cmo'   => 'Chief Marketing Officer (CMO)',
        'md'    => 'Managing Director (MD)',
    ],
    'roomTypes' => ['Single Room', 'Double Room', 'Twin Room', 'Suite', 'Deluxe Room', 'Family Room', 'Executive Room', 'Accessible Room', 'Connecting Room', 'Villa']
];
